import {CustomTheme} from './types';

export const lightTheme: CustomTheme = {
  dark: false,
  colors: {
    primary: '#002DE3',
    secondary: '#5856D6',
    tertiary: '#1B2B48',
    background: '#FFFFFF',
    card: '#F2F2F7',
    text: '#000000',
    border: '#C7C7CC',
    notification: '#FF3B30',
    textPrimary: '#0F1828',
    textSecondary: '',
    btnPrimary: '',
    btnSecondary: '',
    error: '#E94242',
    warning: '#FDCF41',
    success: '#2CC069',
    info: '',
    dark: '#152033',
    shadow: '',
    white: '',
    black: '',
    gray: '',
    weak: '#A4A4A4',
    disabled: '#ADB5BD',
    divider: '#EDEDED',
    offWhite: '#F7F7FC',
    badge: '#D2D5F9',
  },
};

export const darkTheme: CustomTheme = {
  dark: true,
  colors: {
    primary: '#375FFF',
    secondary: '#5E5CE6',
    tertiary: '#1B2B48',
    background: '#0F1828',
    card: '#1C1C1E',
    text: '#FFFFFF',
    border: '#38383A',
    notification: '#FF453A',
    textPrimary: '#F7F7FC',
    textSecondary: '',
    btnPrimary: '',
    btnSecondary: '',
    error: '#E94242',
    warning: '#FDCF41',
    success: '#2CC069',
    info: '',
    dark: '#152033',
    shadow: '',
    white: '',
    black: '',
    gray: '',
    weak: '#A4A4A4',
    disabled: '#ADB5BD',
    divider: '#EDEDED',
    offWhite: '#F7F7FC',
    badge: '#D2D5F9',
  },
};
